In [2]:
import pandas as pd
import json

In [ ]:
 with open("../data/raw/omdb_major_movies.json", "r") as f:
        major_omdb= json.load(f)

In [4]:
major_df = pd.DataFrame(major_omdb)
major_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3

In [14]:
major_df["studio_type"] ="major"
major_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3,major
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1,major
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9,major
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9,major
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3,major

In [10]:
with open("../data/raw/omdb_indie_movies.json", "r") as f:
    indie_omdb= json.load(f)

In [11]:
indie_df = pd.DataFrame(indie_omdb)
indie_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating
0,tt1431045,Deadpool,2016,"Action, Comedy, Sci-Fi",65,8.0
1,tt4154756,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",68,8.4
2,tt4154796,Avengers: Endgame,2019,"Action, Adventure, Sci-Fi",78,8.4
3,tt2395427,Avengers: Age of Ultron,2015,"Action, Adventure, Sci-Fi",66,7.3
4,tt3498820,Captain America: Civil War,2016,"Action, Sci-Fi",75,7.8

In [15]:
indie_df["studio_type"] ="indie"
indie_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt1431045,Deadpool,2016,"Action, Comedy, Sci-Fi",65,8.0,indie
1,tt4154756,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",68,8.4,indie
2,tt4154796,Avengers: Endgame,2019,"Action, Adventure, Sci-Fi",78,8.4,indie
3,tt2395427,Avengers: Age of Ultron,2015,"Action, Adventure, Sci-Fi",66,7.3,indie
4,tt3498820,Captain America: Civil War,2016,"Action, Sci-Fi",75,7.8,indie

In [7]:
omdb_df = pd.concat(
    [major_df,indie_df],
    ignore_index = True
)
omdb_df

,imdbID,Title,Year,Genre,Metascore,imdbRating
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3
...,...,...,...,...,...,...
872,tt3716530,Elle,2016,"Crime, Drama, Thriller",89,7.1
873,tt8267604,Capernaum,2018,Drama,75,8.4
874,tt4005402,Colonia,2015,"Biography, Drama, History",33,7.0
875,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48,6.8
876,tt4540710,Miss Sloane,2016,Drama,64,7.5

In [8]:
omdb_df.to_csv("../data/processed/omdb_movies.csv",index=False)