In [1]:
import pandas as pd
import json

In [2]:
 with open("../data/raw/omdb_major_movies.json", "r") as f:
        major_omdb= json.load(f)

In [3]:
major_df = pd.DataFrame(major_omdb)
major_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3

In [4]:
major_df["studio_type"] ="major"
major_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3,major
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1,major
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9,major
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9,major
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3,major

In [5]:
with open("../data/raw/omdb_indie_movies.json", "r") as f:
    indie_omdb= json.load(f)

In [6]:
indie_df = pd.DataFrame(indie_omdb)
indie_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating
0,tt1431045,Deadpool,2016,"Action, Comedy, Sci-Fi",65,8.0
1,tt4154756,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",68,8.4
2,tt4154796,Avengers: Endgame,2019,"Action, Adventure, Sci-Fi",78,8.4
3,tt2395427,Avengers: Age of Ultron,2015,"Action, Adventure, Sci-Fi",66,7.3
4,tt3498820,Captain America: Civil War,2016,"Action, Sci-Fi",75,7.8

In [7]:
indie_df["studio_type"] ="indie"
indie_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt1431045,Deadpool,2016,"Action, Comedy, Sci-Fi",65,8.0,indie
1,tt4154756,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",68,8.4,indie
2,tt4154796,Avengers: Endgame,2019,"Action, Adventure, Sci-Fi",78,8.4,indie
3,tt2395427,Avengers: Age of Ultron,2015,"Action, Adventure, Sci-Fi",66,7.3,indie
4,tt3498820,Captain America: Civil War,2016,"Action, Sci-Fi",75,7.8,indie

In [8]:
omdb_df = pd.concat(
    [major_df,indie_df],
    ignore_index = True
)
omdb_df.head()

,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt7286456,Joker,2019,"Crime, Drama, Thriller",59,8.3,major
1,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90,8.1,major
2,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40,5.9,major
3,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59,6.9,major
4,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76,7.3,major

In [9]:
omdb_df.to_csv("../data/processed/omdb_movies.csv",index=False)

In [14]:
tmdb_df = pd.read_csv("../data/processed/tmdb_movies.csv")
omdb_df = pd.read_csv("../data/processed/omdb_movies.csv")

In [21]:
merged_df = pd.merge(
    tmdb_df.drop(columns=["studio_type", "title","release_date"]),
    omdb_df,  # 丢弃冲突/冗余列
    left_on="imdb_id",
    right_on="imdbID",
    how="inner"  # 只保留两边都有数据的电影
)
merged_df

,imdb_id,budget,revenue,vote_average,vote_count,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,tt7286456,55000000,1078958629,8.122,27972,tt7286456,Joker,2019,"Crime, Drama, Thriller",59.0,8.3,major
1,tt1392190,150000000,378858340,7.635,24294,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90.0,8.1,major
2,tt1386697,175000000,749200054,5.917,22234,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40.0,5.9,major
3,tt0369610,150000000,1671537444,6.703,21727,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59.0,6.9,major
4,tt0451279,149000000,823970682,7.207,21027,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76.0,7.3,major
...,...,...,...,...,...,...,...,...,...,...,...,...
872,tt3716530,9800000,2341534,6.639,2014,tt3716530,Elle,2016,"Crime, Drama, Thriller",89.0,7.1,indie
873,tt8267604,4000000,64978931,8.150,2007,tt8267604,Capernaum,2018,Drama,75.0,8.4,indie
874,tt4005402,14000000,3621046,7.255,2006,tt4005402,Colonia,2015,"Biography, Drama, History",33.0,7.0,indie
875,tt2261287,30000000,109573511,7.204,2004,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48.0,6.8,indie
876,tt4540710,13000000,9101546,7.405,2000,tt4540710,Miss Sloane,2016,Drama,64.0,7.5,indie

In [22]:
merged_df = merged_df.drop(columns=["imdb_id"])
merged_df

,budget,revenue,vote_average,vote_count,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type
0,55000000,1078958629,8.122,27972,tt7286456,Joker,2019,"Crime, Drama, Thriller",59.0,8.3,major
1,150000000,378858340,7.635,24294,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90.0,8.1,major
2,175000000,749200054,5.917,22234,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40.0,5.9,major
3,150000000,1671537444,6.703,21727,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59.0,6.9,major
4,149000000,823970682,7.207,21027,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76.0,7.3,major
...,...,...,...,...,...,...,...,...,...,...,...
872,9800000,2341534,6.639,2014,tt3716530,Elle,2016,"Crime, Drama, Thriller",89.0,7.1,indie
873,4000000,64978931,8.150,2007,tt8267604,Capernaum,2018,Drama,75.0,8.4,indie
874,14000000,3621046,7.255,2006,tt4005402,Colonia,2015,"Biography, Drama, History",33.0,7.0,indie
875,30000000,109573511,7.204,2004,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48.0,6.8,indie
876,13000000,9101546,7.405,2000,tt4540710,Miss Sloane,2016,Drama,64.0,7.5,indie

In [24]:
merged_df["audience_score"] = merged_df[["vote_average", "imdbRating"]].mean(axis=1)
merged_df

,budget,revenue,vote_average,vote_count,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type,audience_score
0,55000000,1078958629,8.122,27972,tt7286456,Joker,2019,"Crime, Drama, Thriller",59.0,8.3,major,8.2110
1,150000000,378858340,7.635,24294,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90.0,8.1,major,7.8675
2,175000000,749200054,5.917,22234,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40.0,5.9,major,5.9085
3,150000000,1671537444,6.703,21727,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59.0,6.9,major,6.8015
4,149000000,823970682,7.207,21027,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76.0,7.3,major,7.2535
...,...,...,...,...,...,...,...,...,...,...,...,...
872,9800000,2341534,6.639,2014,tt3716530,Elle,2016,"Crime, Drama, Thriller",89.0,7.1,indie,6.8695
873,4000000,64978931,8.150,2007,tt8267604,Capernaum,2018,Drama,75.0,8.4,indie,8.2750
874,14000000,3621046,7.255,2006,tt4005402,Colonia,2015,"Biography, Drama, History",33.0,7.0,indie,7.1275
875,30000000,109573511,7.204,2004,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48.0,6.8,indie,7.0020
876,13000000,9101546,7.405,2000,tt4540710,Miss Sloane,2016,Drama,64.0,7.5,indie,7.4525

In [26]:
merged_df["metascore_10"] = merged_df["Metascore"] / 10
merged_df

,budget,revenue,vote_average,vote_count,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type,audience_score,metascore_10
0,55000000,1078958629,8.122,27972,tt7286456,Joker,2019,"Crime, Drama, Thriller",59.0,8.3,major,8.2110,5.9
1,150000000,378858340,7.635,24294,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90.0,8.1,major,7.8675,9.0
2,175000000,749200054,5.917,22234,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40.0,5.9,major,5.9085,4.0
3,150000000,1671537444,6.703,21727,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59.0,6.9,major,6.8015,5.9
4,149000000,823970682,7.207,21027,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76.0,7.3,major,7.2535,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,9800000,2341534,6.639,2014,tt3716530,Elle,2016,"Crime, Drama, Thriller",89.0,7.1,indie,6.8695,8.9
873,4000000,64978931,8.150,2007,tt8267604,Capernaum,2018,Drama,75.0,8.4,indie,8.2750,7.5
874,14000000,3621046,7.255,2006,tt4005402,Colonia,2015,"Biography, Drama, History",33.0,7.0,indie,7.1275,3.3
875,30000000,109573511,7.204,2004,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48.0,6.8,indie,7.0020,4.8
876,13000000,9101546,7.405,2000,tt4540710,Miss Sloane,2016,Drama,64.0,7.5,indie,7.4525,6.4

In [28]:
merged_df["gap"] = merged_df["audience_score"] - merged_df["metascore_10"]
merged_df

,budget,revenue,vote_average,vote_count,imdbID,Title,Year,Genre,Metascore,imdbRating,studio_type,audience_score,metascore_10,gap
0,55000000,1078958629,8.122,27972,tt7286456,Joker,2019,"Crime, Drama, Thriller",59.0,8.3,major,8.2110,5.9,2.3110
1,150000000,378858340,7.635,24294,tt1392190,Mad Max: Fury Road,2015,"Action, Adventure, Sci-Fi",90.0,8.1,major,7.8675,9.0,-1.1325
2,175000000,749200054,5.917,22234,tt1386697,Suicide Squad,2016,"Action, Adventure, Fantasy",40.0,5.9,major,5.9085,4.0,1.9085
3,150000000,1671537444,6.703,21727,tt0369610,Jurassic World,2015,"Action, Adventure, Sci-Fi",59.0,6.9,major,6.8015,5.9,0.9015
4,149000000,823970682,7.207,21027,tt0451279,Wonder Woman,2017,"Action, Adventure, Fantasy",76.0,7.3,major,7.2535,7.6,-0.3465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,9800000,2341534,6.639,2014,tt3716530,Elle,2016,"Crime, Drama, Thriller",89.0,7.1,indie,6.8695,8.9,-2.0305
873,4000000,64978931,8.150,2007,tt8267604,Capernaum,2018,Drama,75.0,8.4,indie,8.2750,7.5,0.7750
874,14000000,3621046,7.255,2006,tt4005402,Colonia,2015,"Biography, Drama, History",33.0,7.0,indie,7.1275,3.3,3.8275
875,30000000,109573511,7.204,2004,tt2261287,Leap!,2016,"Animation, Adventure, Comedy",48.0,6.8,indie,7.0020,4.8,2.2020
876,13000000,9101546,7.405,2000,tt4540710,Miss Sloane,2016,Drama,64.0,7.5,indie,7.4525,6.4,1.0525

In [29]:
merged_df.to_csv("../data/processed/movies_clean.csv", index=False)